### ISSUE TITLE
some errors on demo 

### ISSUE THREAD

**Issue by Robinatp** [mystic123/tensorflow-yolo-v3#1]
hi guys,this work is greate for me , and I get a lot of knowledge from this repository.But I find two error on it.
First, there is a ValueError as follows:
"ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("detector/yolo-v3/Tile_1:0", shape=(507, 2), dtype=int32)'"
Second, you make a small mistake when saving a detected image in the end.If you want save the origin image ,you should draw_boxes with its own with and height rather than  drawing the img with FLAGS.size.

The follows is my diffs for the errors:

diff --git a/demo.py b/demo.py
index b3c38ed..dcedeaa 100644
--- a/demo.py
+++ b/demo.py
@@ -8,10 +8,10 @@ from yolo_v3 import yolo_v3, load_weights, detections_boxes, non_max_suppression
 
 FLAGS = tf.app.flags.FLAGS
 
-tf.app.flags.DEFINE_string('input_img', '', 'Input image')
-tf.app.flags.DEFINE_string('output_img', '', 'Output image')
-tf.app.flags.DEFINE_string('class_names', 'coco.names', 'File with class names')
-tf.app.flags.DEFINE_string('weights_file', 'yolov3.weights', 'Binary file with detector weights')
+tf.app.flags.DEFINE_string('input_img', 'images/person.jpg', 'Input image')
+tf.app.flags.DEFINE_string('output_img', 'out/detected.jpg', 'Output image')
+tf.app.flags.DEFINE_string('class_names', 'model_data/coco_classes.txt', 'File with class names')
+tf.app.flags.DEFINE_string('weights_file', 'weight/yolov3.weights', 'Binary file with detector weights')
 
 tf.app.flags.DEFINE_integer('size', 416, 'Image size')
 
@@ -54,7 +54,7 @@ def main(argv=None):
     inputs = tf.placeholder(tf.float32, [None, FLAGS.size, FLAGS.size, 3])
 
     with tf.variable_scope('detector'):
      -        detections = yolo_v3(inputs, len(classes), data_format='NCHW')
     +        detections = yolo_v3(inputs, len(classes), data_format='NHWC')
         load_ops = load_weights(tf.global_variables(scope='detector'), FLAGS.weights_file)
 
     boxes = detections_boxes(detections)
@@ -62,14 +62,17 @@ def main(argv=None):
     with tf.Session() as sess:
         sess.run(load_ops)
 
      +        writer =tf.summary.FileWriter("logs/",graph = sess.graph)
      +        writer.close()
         detected_boxes = sess.run(boxes, feed_dict={inputs: [np.array(img_resized, dtype=np.float32)]})
 
     filtered_boxes = non_max_suppression(detected_boxes, confidence_threshold=FLAGS.conf_threshold,
                                          iou_threshold=FLAGS.iou_threshold)
 
     -    draw_boxes(filtered_boxes, img, classes, (FLAGS.size, FLAGS.size))
     +    draw_boxes(filtered_boxes, img_resized, classes, (FLAGS.size, FLAGS.size))
 
      -    img.save(FLAGS.output_img)
      +    img_resized.save(FLAGS.output_img)
 
 
 if __name__ == '__main__':
diff --git a/yolo_v3.py b/yolo_v3.py
index 098e65c..7183b28 100644
--- a/yolo_v3.py
+++ b/yolo_v3.py
@@ -61,7 +61,7 @@ def _darknet53_block(inputs, filters):
 
 
 @tf.contrib.framework.add_arg_scope
-def _fixed_padding(inputs, kernel_size, *args, mode='CONSTANT', **kwargs):
+def _fixed_padding(inputs, kernel_size, mode='CONSTANT', **kwargs):
     """
     Pads the input along the spatial dimensions independently of input size.
 
@@ -146,7 +146,7 @@ def _detection_layer(inputs, num_classes, anchors, img_size, data_format):
     box_centers = box_centers * stride
 
     anchors = tf.tile(anchors, [dim, 1])
      -    box_sizes = tf.exp(box_sizes) * anchors
      +    box_sizes = tf.exp(box_sizes) * tf.to_float(anchors)
     box_sizes = box_sizes * stride
 
     detections = tf.concat([box_centers, box_sizes, confidence], axis=-1)

**Comment by mystic123** [comment]
1) I wasn't able to reproduce this error. Can you provide more details?
2) it is OK, I want to draw boxes on the image in original size (this is why I rescale detected sizes).

**Comment by mystic123** [comment]
Great! I added information that I used Python 3.5 in README
