### ISSUE TITLE
What is the output node?

### ISSUE THREAD

**Issue by linux-devil** [mystic123/tensorflow-yolo-v3#13]
I want to know output node

**Comment by mystic123** [comment]
In commit @dd09029 I named detections node, so now output node is 'detections'. The input node is the placeholder defined in demo.py

**Comment by linux-devil** [comment]
I am using latest commit, I made changes to save session using `saver.save(sess,export_dir)`
Further I use save_freeze.py to freeze graph which takes output node as parameter and it fails while running it using "detections" 
you can find save_freeze.py here : 
https://github.com/linux-devil/lstm_practice/blob/master/save_freeze.py
**command** : 
python save_freeze.py --model_dir "/xxxx/yolov3_checkpoint" --output_node_names "detections"

Following is the graph as visualized on tensorboard:
![graph_large_attrs_key _too_large_attrs limit_attr_size 1024 run 1](https://user-images.githubusercontent.com/307810/42687825-af4ed40a-86b7-11e8-9e2c-623755366b9f.png)
There is no node named "tensorboard"

**Comment by linux-devil** [comment]
Any thoughts?

**Comment by mystic123** [comment]
@linux-devil, there should be node named '<scope>/yolo-v3/detections'. Check this code:

`import tensorflow as tf
import numpy as np
from yolo_v3 import yolo_v3, load_weights, detections_boxes

inputs = tf.placeholder(tf.float32, [1, 416, 416, 3])

with tf.variable_scope('detector'):
    detections = yolo_v3(inputs, 80)

t = tf.get_default_graph().get_tensor_by_name('detector/yolo-v3/detections:0')

print(t)`

**Comment by STG284** [comment]
while running in android using .pb file, I am getting no node "detections"
: -
java.lang.RuntimeException: Node 'detections' does not exist in model 'file:///android_asset/tiny_graph.pb'

So indeed there is no node detections. What to do?
