### ISSUE TITLE
ValueError: cannot reshape array of size 60663 into shape (258,256,1,1)

### ISSUE THREAD

**Issue by liuchang8am** [mystic123/tensorflow-yolo-v3#15]
Following [how to demo here](https://github.com/mystic123/tensorflow-yolo-v3#how-to-run-the-demo) , I got an error:

```
File "/home/lc/codes/tensorflow-yolo-v3/demo.py", line 58, in main
    load_ops = load_weights(tf.global_variables(scope='detector'), FLAGS.weights_file)
  File "/home/lc/codes/tensorflow-yolo-v3/yolo_v3.py", line 298, in load_weights
    var_weights = weights[ptr:ptr + num_params].reshape((shape[3], shape[2], shape[0], shape[1]))
ValueError: cannot reshape array of size 60663 into shape (258,256,1,1)
```

If helpful, the debugging info is:

![image](https://user-images.githubusercontent.com/1009550/43085539-cbfd041e-8ecd-11e8-90b3-87030a0e41c3.png)

![image](https://user-images.githubusercontent.com/1009550/43085395-83bdbaea-8ecd-11e8-924c-381fdfff98e0.png)

Any thoughts what might be wrong? Awesome work btw!

**Comment by liuchang8am** [comment]
Nevermind, it turns out I had an blank line in coco.names file.

**Comment by abuzahid** [comment]
This happens for problem in (.names) file. You should check tow things to solve this.
1. If you are training on all classes please check if there is extra new line at the last of class names.
2. If you are training on specific some classes please remove the extra class from (.names) file either you used all class names during training.
