### ISSUE TITLE
Input format RGB or BGR?

### ISSUE THREAD

**Issue by nguyeho7** [mystic123/tensorflow-yolo-v3#2]
What is the expected image format? I know pillow loads images as RGB, so if I were to load images from cv2 in BGR format, would I have to transpose them?

**Comment by mystic123** [comment]
The input format is RGB, so you have to transpose the channels.
I will add this information to the docstring.

**Comment by LucasMahieu** [comment]
@mystic123 can you provide any evidence that the official implementation of yolov3 takes as input RGB image ? please

**Comment by mystic123** [comment]
https://github.com/pjreddie/darknet/issues/427

**Comment by LucasMahieu** [comment]
Thanks @mystic123
