### ISSUE TITLE
Code doesn't run on CPU

### ISSUE THREAD

**Issue by ildarlomov** [mystic123/tensorflow-yolo-v3#21]
Good implementation, thx you!

I've tried to run your demo code in Docker container with 1.8 tensorflow on my Mac and received an error `UnimplementedError (see above for traceback): Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: detector/darknet-53/Conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](detector/truediv, detector/darknet-53/Conv/weights/read)]]`
is it hard to fix this directly in your implementation?

**Comment by mystic123** [comment]
Well, this exception is pretty self-explanatory: conv implementation does not support "NCHW" data format on CPU. To fix this, you need to either run it on GPU or change `data_format` parameter in call of `yolo_v3` to "NHWC" (eg. line 57 of demo.py)
