### ISSUE TITLE
No such file or director: 'coco.names'

### ISSUE THREAD

**Issue by spencerkraisler** [mystic123/tensorflow-yolo-v3#32]

**Comment by robertlugg** [comment]
It would be good to update the instructions on how to get this.  I was able to run by downloading the file from GitHub:
wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names

**Comment by mystic123** [comment]
The instruction is already available. Just read README.md

**Comment by robertlugg** [comment]
I may be looking in the wrong place.  Do you mean:
https://raw.githubusercontent.com/mystic123/tensorflow-yolo-v3/master/README.md

I don't see a reference to the coco.names but I may have missed something elsewhere.

**Comment by mystic123** [comment]
Yes, just read the linked tutorial

**Comment by robertlugg** [comment]
I see no instruction in the .md nor at:
https://itnext.io/implementing-yolo-v3-in-tensorflow-tf-slim-c3c55ff59dbe
for getting the coco.names file.

**Comment by spencerkraisler** [comment]
Why isn't coco.names part of the repository...? It seems important since the demo can't run without it.

**Comment by spencerkraisler** [comment]
There is no tutorial on how to implement coco.names.

**Comment by mystic123** [comment]
Ok, sorry my bad, I as sure that I linked it somewhere. I will add url to the README. Sorry about that.
