### ISSUE TITLE
How do I install coco.names?

### ISSUE THREAD

**Issue by spencerkraisler** [mystic123/tensorflow-yolo-v3#34]
I read through the tutorial and readme. Nothing really about coco.names. I think I downloaded it but now I'm getting "UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 221: character maps to <undefined>" whenever I run demo.py.

**Comment by mystic123** [comment]
Please submit information about at least Python version, OS, Tensorflow version
