### ISSUE TITLE
Possible error in the non max supression function

### ISSUE THREAD

**Issue by erivera1802** [mystic123/tensorflow-yolo-v3#35]
https://github.com/mystic123/tensorflow-yolo-v3/blob/fb9f5439d90ecff255b008e9c9d9e3b8ac4813da/yolo_v3.py#L392

I was testing the code with an Image with multiple objects of the same classes, and I noted that the scores of those objects were always the same. I am not really sure if that is correct; that's why I looked down the code and found that in the nms function, when the cls_boxes's first row is discarded (To proceed with the next box), but the first row of cls_scores isnt. That means, all the objects of the same classes are saved with the scores of the first object (With the highest score). My solution was just to discard the first row of cls_scores too, exactly below the line 392:
cls_scores = cls_scores[1:]

If it isnt correct, I would like to know why,
Regards

**Comment by mystic123** [comment]
Good point, could you, please, submit PR with this fix?

**Comment by mystic123** [comment]
Yes, you need to submit PR. Check this tutorial:
https://yangsu.github.io/pull-request-tutorial/

pon., 22 paź 2018 o 15:25 erivera1802 <notifications@github.com> napisał(a):

**Comment by erivera1802** [comment]
Done
