### ISSUE TITLE
Your Yolo v3 implementation seems wrong

### ISSUE THREAD

**Issue by LucasMahieu** [mystic123/tensorflow-yolo-v3#51]
According to [the original implementation](https://github.com/pjreddie/darknet/blob/680d3bde1924c8ee2d1c1dea54d3e56a05ca9a26/cfg/yolov3.cfg)

I don't see the 2 255 conv : 
```
[convolutional]
size=1
stride=1
pad=1
filters=255
activation=linear
```

Are you sure the implementation is correct ?

**Comment by mystic123** [comment]
Hi,
This layer is a detection layer. The number of filters, 255, comes from equations: num_anchors * (num_classes + 5). Yolo trained on COCO detects 80 classes and has 3 anchors for each size: (3 * (80 + 5) = 255).
In my implementation, this layer is defined in` _detection_layer, line 117 (yolov3.py)`

**Comment by LucasMahieu** [comment]
Ok ! Thanks ! So what about https://github.com/mystic123/tensorflow-yolo-v3/issues/40
