### ISSUE TITLE
Cannot reshape array of size 391694 into shape (512,256,3,3) for Yolov3-Tiny

### ISSUE THREAD

**Issue by AlexeyAB** [mystic123/tensorflow-yolo-v3#79]
I just downloaded 3 files:
* https://pjreddie.com/media/files/yolov3-tiny.weights
* https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg
* https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names

Run this command:
`python3 convert_weights_pb.py --class_names coco.names --data_format NHWC --weights_file yolov3-tiny.weights --tiny`

and get an error: 

![image](https://user-images.githubusercontent.com/4096485/60439498-ac489a00-9c1b-11e9-951c-a13d479a83cb.png)

https://github.com/mystic123/tensorflow-yolo-v3/blob/ed60b9087b04e1d9ca40f8a9d8455d5c30c7c0d3/utils.py#L114-L115

I saw similar issues but with other error messages than `... into shape (512,256,3,3)`

**Comment by stangier** [comment]
I have a similar problem when using YoloV3 (**not** tiny). Please see attached screenshot for more information. The Error Occurs at the same position as your error @AlexeyAB 

![image](https://user-images.githubusercontent.com/7353918/60528088-a9a08000-9cc1-11e9-8e2f-a0adf30d5f19.png)

As far as I know, the problem is caused by the fact that `ptr + num_params` is larger than the length of the array `weights` so the actual number of elements in the area `ptr:ptr + num_params` is smaller than `ptr + num_params`. This means that the array cannot be resized because the calculation in line 112 doesn't fit to the lenght of the array. 

![image](https://user-images.githubusercontent.com/7353918/60528169-db194b80-9cc1-11e9-97fc-62e662352809.png)

**Comment by dexception** [comment]
@AlexeyAB 
Did u use this command ?

git checkout ed60b90

For more info:
https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html

Also OpenVino has a bug for yolov3-tiny conversion and it has not been resolved as of yet for 2019R1.

https://github.com/opencv/dldt/issues/151

**Comment by AlexeyAB** [comment]
@dexception 

> Did u use this command ?
> 
> git checkout ed60b90

No, It seems that ed60b90 is the last commit, so it isn't necessary yet: https://github.com/mystic123/tensorflow-yolo-v3/commits/master

> For more info:
> https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html

Yes, I used this manual.

Do you know, can we use OpenCV-dnn module with Myriad VPU? If we compiled OpenCV with OpenVINO backend: https://github.com/opencv/opencv/wiki/Intel's-Deep-Learning-Inference-Engine-backend

**Comment by stangier** [comment]
I solved this issue for me. Apparently I trained with a YoloV3 **Tiny** configuration but I thought that it was a full YoloV3 configuration. After using the `--tiny` flag to convert my model it worked flawlessly.

**Comment by AlexeyAB** [comment]
@stangier 

Can you convert default yolov3-tiny model by using this command?
`python3 convert_weights_pb.py --class_names coco.names --data_format NHWC --weights_file yolov3-tiny.weights --tiny`

* https://pjreddie.com/media/files/yolov3-tiny.weights
* https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg

**Comment by violet17** [comment]
> @stangier
> 
> Yes, I solved this issue.
> The problem was windows newline character `\r\n` at the end of command in sh-file.
> 
> `python3 convert_weights_pb.py --class_names coco.names --data_format NHWC --weights_file yolov3-tiny.weights --tiny`
> 
> * https://pjreddie.com/media/files/yolov3-tiny.weights
> * https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg

How to solve it?

**Comment by Ibanez1408** [comment]
> I solved this issue for me. Apparently I trained with a YoloV3 **Tiny** configuration but I thought that it was a full YoloV3 configuration. After using the `--tiny` flag to convert my model it worked flawlessly.

I have the same error. If I use the yolov3-320 I can run it fine, but when I use the yolov3-tiny, I get the error.

**Comment by freedom9393** [comment]
> @stangier
> 
> Yes, I solved this issue.
> The problem was windows newline character `\r\n` at the end of command in sh-file.
> 
> `python3 convert_weights_pb.py --class_names coco.names --data_format NHWC --weights_file yolov3-tiny.weights --tiny`
> 
> * https://pjreddie.com/media/files/yolov3-tiny.weights
> * https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg

I did not understand your reply. Could you explain more deteailed, please?
