### ISSUE TITLE
Convert .pb to .tflite file

### ISSUE THREAD

**Issue by DoriHp** [mystic123/tensorflow-yolo-v3#89]
I'm facing with running yolov3-tiny on mobile device. Can anyone show me how to convert .pb file to .tflite so I can use it with tensorflow-lite?
Thanks in advance

**Comment by nscotto** [comment]
Same, I have not been able to freeze the graph, can someone provide details instructions specific to this model on how to do it please?

**Comment by peace195** [comment]
@DoriHp I did it here: https://github.com/peace195/tensorflow-lite-yolo-v3

**Comment by DoriHp** [comment]
@peace195 I found your repo and tried both it and built-in tflite converter of tensorflow. Both worked well. I also gave you a star for your effort. The problem I'm facing now is implement it on android device. I'm not a professional in machine learning so it will be very helpful if you can give me a suggestion to resolve it.

**Comment by nscotto** [comment]
I have just tried it as well, conversion worked well, another star for you! ;)
Same as DoriHP, I think some details on how to recover the probabilities and the boxes would be really appreciated.
Thank you.

**Comment by peace195** [comment]
@nscotto Thanks! I will update it when I have time.

**Comment by peace195** [comment]
@nscotto @DoriHp Here is the example of tflite usage.
https://github.com/peace195/tensorflow-lite-yolo-v3/blob/master/tflite_example.py

It is in python code. I will update Android and iOS version later.
